services:
  journal-entries-ms:
    build:
      context: \seller-journal-entries\.
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 40M
      mode: replicated
      replicas: 3
    hostname: journal-entries-host
    networks:
      - journal_entries_network
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=journal-entries-db;Database=db-hml;Username=postgres;Password=Senha123!;Timeout=60;CommandTimeout=60
    depends_on:
      - journal-entries-db
      - daily-consolidated-balance-ms

  daily-consolidated-balance-ms:
    build:
      context: \daily-consolidated-balance\.
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 40M
      mode: replicated
      replicas: 3
    hostname: daily-consolidated-balance-host
    networks:
      - journal_entries_network
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=journal-entries-db;Database=db-hml;Username=postgres;Password=Senha123!;Timeout=60;CommandTimeout=60

  journal-entries-db:
    image: postgres:17.2
    container_name: journal-entries-db
    hostname: journal-entries-db
    environment:
      - POSTGRES_DB=db-hml
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Senha123!
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf

    networks:
      - journal_entries_network

  nginx-journal:
    image: nginx:latest
    ports:
      - "5001:5001"
    volumes:
      - ./nginx/journal-entries/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - journal-entries-ms
    networks:
      - journal_entries_network

  nginx-daily:
    image: nginx:latest
    ports:
      - "5002:5002"
    volumes:
      - ./nginx/daily-balance/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - daily-consolidated-balance-ms
    networks:
      - journal_entries_network

networks:
  journal_entries_network:
    driver: bridge

volumes:
    pgdata: