services:
  journal-entries-ms:
    build:
      context: \seller-journal-entries\.
      dockerfile: Dockerfile
    container_name: journal-entries-api
    hostname: journal-entries-host
    ports:
    - "5001:8080"
    networks:
      - journal_entries_network
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=journal-entries-db;Database=db-hml;Username=postgres;Password=Senha123!
    depends_on:
      - journal-entries-db

  daily-consolidated-balance-ms:
    build:
      context: \daily-consolidated-balance\.
      dockerfile: Dockerfile
    container_name: daily-consolidated-balance-api
    hostname: daily-consolidated-balance-host
    ports:
    - "5002:8080"
    networks:
      - journal_entries_network
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=journal-entries-db;Database=db-hml;Username=postgres;Password=Senha123!
    depends_on:
      - journal-entries-ms

  journal-entries-db:
    image: postgres:17.2
    container_name: journal-entries-db
    hostname: journal-entries-db
    environment:
      - POSTGRES_DB=db-hml
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Senha123!
    ports:
      - "35432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - journal_entries_network

networks:
  journal_entries_network:

volumes:
    pgdata: